### ISSUE TITLE
Errors are silenced when local storage quota is exceeded

### ISSUE THREAD

**Issue by davidholyko** [polemius/recoil-persist#12]
<img width="1024" alt="Screen Shot 2021-01-11 at 2 09 53 PM" src="https://user-images.githubusercontent.com/20917792/104227028-bce3ee00-5416-11eb-9dab-bda061c8dd2a.png">

Can we unsilence the errors

**Comment by polemius** [comment]
Thank you for adding this issue.
I have added showing in console all errors in [0.9.0](https://github.com/polemius/recoil-persist/commit/c8c571dc23eafe04c0ada66bb3a70ff52edcddd7)

**Comment by davidholyko** [comment]
Awesome! :D
