### ISSUE TITLE
Is recoilPersist paths argument type correct?

### ISSUE THREAD

**Issue by fekete965** [polemius/recoil-persist#18]
I am just wondering if the **paths** argument's type in the recoilPersist shouldn't be an Array<string> instead of string?

**Comment by polemius** [comment]
Just released the 1.2.0 version with @rhys-saldanha type fix. Please check it

**Comment by fekete965** [comment]
Ah sorry, I missed that!

**Comment by polemius** [comment]
@fekete965 No problem at all! Thank you for adding issue 👍
