### ISSUE TITLE
Support for asynchronous Storage (React Native)

### ISSUE THREAD

**Issue by BenJeau** [polemius/recoil-persist#19]
Using this package does not work with React Native since their Storage API (aka the `AsyncStorage` API, here's a link to their [docs](https://react-native-async-storage.github.io/async-storage/docs/api)) is asynchronous and this package does not seem to support an asynchronous Storage API. This issue is to simply open the conversation this subject.

The following is what I used to set the storage:

```jsx
const {persistAtom} = recoilPersist({
  storage: AsyncStorage,
});
```

The error message:

There's an error here since `toParse` is a Promise.
![image](https://user-images.githubusercontent.com/22248828/106813616-3b5f3480-663f-11eb-8980-32f78a61797b.png)

Looking at the code, you could check if `getItem()` or/and `setItem()` is a promise to know if its async or not, then transform the functions to be async. This is potentially a naïve idea, but I'm not sure how it could be implemented otherwise, maybe you have a better idea on its implementation.

**Comment by polemius** [comment]
@BenJeau Thank you for raising issue. I have updated the library and release and new version 2.1.0. Please try it now.

**Comment by BenJeau** [comment]
Thank you for the fast fix/update @polemius! I just pulled the latest version, there's no error and it seems to work well
