### ISSUE TITLE
Deploy Demo to GitHub Pages

### ISSUE THREAD

**Issue by VikashKothary** [polemius/recoil-persist#23]
You've got a `demo` in your tests folder. I think it would be beneficial to deploy it to GitHub Pages so that users can see how his library works without having to clone the repository.

**Comment by polemius** [comment]
@VikashKothary Thank you for the idea! I have just deployed: https://polemius.dev/recoil-persist/

**Comment by VikashKothary** [comment]
Looks good. 

Now it's deployed it might be worth developing the demo further but I'm sure that'll come with time.

Thanks for doing this.
