### ISSUE TITLE
Nextjs is broken again

### ISSUE THREAD

**Issue by lucax88x** [polemius/recoil-persist#24]
https://github.com/polemius/recoil-persist/blob/bd7ecc3028c16ebfa8415d3a465831d16565c546/src/index.ts#L24

Hey man, nextjs is broken again because you are getting localStorage before the window check..

**Comment by polemius** [comment]
@lucax88x Sorry about that. Released fix in 2.2.0

**Comment by lucax88x** [comment]
No worries and thanks man.

**Comment by vitorcamachoo** [comment]
Im getting that error on 2.2.0.

**Comment by polemius** [comment]
@vitorcamachoo please try the new version 2.3.0
