### ISSUE TITLE
Fatal error when hydrating state

### ISSUE THREAD

**Issue by lmartins** [polemius/recoil-persist#31]
I've recently started seeing the following error:
`Uncaught (in promise) TypeError: Cannot read property '__tag' of null`
referring to this line: https://github.com/polemius/recoil-persist/blob/58a9bec906d9af0fd599a034a16374a3688b8971/src/index.ts#L49

Any idea of what could be causing it?

**Comment by polemius** [comment]
@lmartins Thank you for adding the issue. I have released a new 2.4.0 version with the fix. Please check the new version.

**Comment by lmartins** [comment]
@polemius that was quick, thank you!
