### ISSUE TITLE
Update peer dependency

### ISSUE THREAD

**Issue by henriq-88** [polemius/recoil-persist#33]
I'm receiving this error when I'm installing the latest `recoil-persist` version right after installing `recoil`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@1.0.0
npm ERR! Found: recoil@0.2.0
npm ERR! node_modules/recoil
npm ERR!   recoil@"0.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer recoil@"^0.1.2" from recoil-persist@2.5.0
npm ERR! node_modules/recoil-persist
npm ERR!   recoil-persist@"*" from the root project
```

These are my current npm and node versions:
```
$ npm -v
7.5.3
$ node -v
v15.10.0
```

**Comment by polemius** [comment]
I have updated recoil peer dependency to version 0.3.1

**Comment by jacobdubail** [comment]
@polemius Could we do the same for recoil@"0.4.0"? I don't see any obvious breaking changes in recoil.

**Comment by polemius** [comment]
@jacobdubail I have updated recoil peer dependency to 0.4.0 version. The new recoil-persist 3.0.0 version just published

**Comment by jacobdubail** [comment]
Thank you! Much appreciated.

**Comment by rtritto** [comment]
@polemius new recoil [v0.5.1](https://github.com/facebookexperimental/Recoil/releases/tag/0.5.1) was released!

**Comment by rtritto** [comment]
@polemius _recoil_ [v0.6.1](https://github.com/facebookexperimental/Recoil/releases/tag/0.6.0) was released

**Comment by rtritto** [comment]
@polemius recoil [v0.7.0](https://github.com/facebookexperimental/Recoil/releases/tag/0.7.0)
