### ISSUE TITLE
Nextjs Incompatibility

### ISSUE THREAD

**Issue by lucax88x** [polemius/recoil-persist#6]
Unfortunately, this library cannot work with a nextjs project.

I managed to make it work, but I had to change too many stuffs in order to make it work and I cannot make a pr because of that.

If you want, we can think together about this topic.

**Comment by Shahriar-Shakil** [comment]
@lucax88x I  faced the same issue.  did you find any solution

**Comment by lucax88x** [comment]
Yeah, but it's too late, recoil changed the strategy.

https://recoiljs.org/docs/guides/atom-effects/

With this feature it should be much easier.

**Comment by bluelovers** [comment]
https://github.com/bluelovers/ws-react/blob/master/packages/%40lazy-react/recoil-persist/index.ts

**Comment by polemius** [comment]
@lucax88x Thank you for adding this issue. Are you interesting to send a PR with changes?
