### ISSUE TITLE
Update peerDependency of recoil 

### ISSUE THREAD

**Issue by eggplants** [polemius/recoil-persist#60]
Latest recoil's version is 0.7.2. Please update peerDependency if possible.
https://github.com/facebookexperimental/Recoil/releases/tag/0.7.2

**Comment by olasunkanmi1** [comment]
@eggplants I’m stuck here also. You got an alternative?

**Comment by eggplants** [comment]
Official workaround is available: https://recoiljs.org/docs/guides/atom-effects/#local-storage-persistence

But it is too tedious.

**Comment by polemius** [comment]
I published a new version 4.2.0 with updated peerDependency.

**Comment by eggplants** [comment]
Thank you for your support so much!
