### ISSUE TITLE
Make parseState or getState configurable

### ISSUE THREAD

**Issue by tpict** [polemius/recoil-persist#75]
Would it be possible to override one of these functions in the `config` option so we can store objects which aren't trivially deserialized from JSON? e.g. `Set`

**Comment by polemius** [comment]
You could pass `Storage` implementation to `recoilPersist` as storage, and change behavior of `getItem` and `setItem`.
For example this storage encode everything in base64 and save it in localstorage. On read get the value from localstorage, decode and return it:

```js
import { encode, decode } from 'js-base64';

const localStorageBase64 = () => {
  return {
    setItem: (key, value) => {
      localStorage.setItem(key, encode(value))
    },
    getItem: (key) => {
      const a =  localStorage.getItem(key)
      return decode(a || '')
    },
    clear: () => {
      localStorage.clear()
    },
  }
}

const { persistAtom } = recoilPersist({ key: 'abc1234', storage: localStorageBase64() })
```
