### ISSUE TITLE
can not install 5.0.0 in npm

### ISSUE THREAD

**Issue by lhojun** [polemius/recoil-persist#79]
I can not install 5.0.0 version in my project.

It appears to be installed after `npm install recoil-persist` or `yarn add recoil-persist`, 
but my react project is not build with `Module not found: Error: Can't resolve 'recoil-persist'` error.
(but there is dependency in `package.json`)

i was able to fix the problem using 4.2.0,
but it seems that there is a problem with version 5.0.0

my project env : (ubuntu 20.04.6 / node 20.3.1 / npm 9.6.7 / react 18.2.0 / recoil 0.7.7)

**Comment by polemius** [comment]
Thank you for raising issue! Fixed in 5.0.1
